### ISSUE TITLE
Cannot boot GVWIN

### ISSUE THREAD

**Issue by californiaelectric** [devhawala/dwarf#2]
I just did a fresh "express" install of GVWindows under windows 3.1.

using that GVWIN.DSK and GVWIN.GRM I receive the following message trying to start it under dwarf:
ERR: -------------------------------------- unimplemented ESC-opcode 0xA4
dev.hawala.dmachine.engine.Cpu$MesaERROR: DbgSubst :: BWS boot, uncaught signal : BWSSTUFFA? HFWBWSSTUFFA? A   [ 9999 7649 0223 1919 2021 0606 0140 0008 0623 0223 1919 2021 0606 0141 0001 0000 ]
	at dev.hawala.dmachine.dwarf.DebuggerSubstituteMpHandler.newMP(DebuggerSubstituteMpHandler.java:130)
	at dev.hawala.dmachine.engine.Cpu.setMP(Cpu.java:273)
	at dev.hawala.dmachine.engine.opcodes.Ch03_Memory_Organization.lambda$15(Ch03_Memory_Organization.java:162)
	at dev.hawala.dmachine.engine.Opcodes.lambda$0(Opcodes.java:187)
	at dev.hawala.dmachine.engine.Opcodes.dispatch(Opcodes.java:182)
	at dev.hawala.dmachine.engine.Cpu.processor(Cpu.java:930)
	at dev.hawala.dmachine.Dwarf.lambda$1(Dwarf.java:504)
	at java.lang.Thread.run(Thread.java:748)

***
*** processor exited: DbgSubst :: BWS boot, uncaught signal : BWSSTUFFA? HFWBWSSTUFFA? A   [ 9999 7649 0223 1919 2021 0606 0140 0008 0623 0223 1919 2021 0606 0141 0001 0000 ]
***

Is there anything I need to do to the globalview disk image while it is running under windows to be able to move it to dwarf? I have never been able to launch a GVWIN image under the yokwe emulator either.

**Comment by devhawala** [comment]
Hello,

no, a special preparation of the GVWIN disk image is not necessary, except for the things mentioned in the readme (little display problem for the help icon, no support for PC access or local printing or help or ...) GVWIN should work

My usual recommendation about 30 years ago would have been to add the d switch and do a remote debug session of your machine.

As Dwarf does not have a network access (and not having the development environment allowing a debug session), this won't work. So I have only the usual developer's excuse: it works on my local machine...

However, maybe some configuration entry hints from my Dwarf properties file can be useful:

`switches = Oy{|}\\346\\347\\350\\377`
`displayWidth = 1024`
`displayHeight = 640`
`addressBitsVirtual = 24`
`addressBitsReal = 23`

This gives 16 MByte virtual memory and large heap paging space; i remember having read somewhere that GlobalView is _very_ memory demanding.

Hope that a larger memory helps,  
Hans

**Comment by californiaelectric** [comment]
Thanks for the tips.

Where did you get the GVWIN001.DSK from? is it yours from years ago, or from the version of GVWin that are out there on the internet or in archive.org?

I have XDE for GV and a few other pieces to enable developer mode in GV but so far nothing has helped me launch GVWin without using the N bootswitch. And as soon as GVWrite, for example, runs, the whole thing crashes.

I will try your configuration.

**Comment by californiaelectric** [comment]
This is very intersting.
I changed the addressBits as you suggested.
i have one GVWIN001.DSK from last June that will launch in dwarf! I don't know what is different about that file but it works.
The only issue is that no changes are saved - the title bar of the window says Read-Only. Any ideas?

**Comment by californiaelectric** [comment]
Ah ha!
If the DSK or floppy files are in the same directory as dwarf.jar they will be mounted read only.
Perhaps this is due to some java security feature?
I'll open a new issue and close this one since dwarf boots, at least on some of my GVWin disk images.
